kind: pipeline
name: build
type: kubernetes

# test           
steps:
- name: build
  image: node:17
  commands:
  - npm install
  - export IMAGE_TAG=dr_$DRONE_BRANCH.$DRONE_BUILD_NUMBER
  - echo $IMAGE_TAG
  - export
- name: push
  image: plugins/kaniko:1.5.0
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: chicagozer/hellonode
    dockerfile: Dockerfile
    tags: ${IMAGE_TAG},latest
