{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hellonode.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
    # share a single ALB with all ingress rules with search-app-ingress
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName }} 
{{ if .Values.ingress.use_tls }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateARN }}
{{ end }}
spec:
  rules:
  - host: "{{ $fullName }}.{{ .Release.Namespace }}.{{ .Values.domain }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
{{- end }}
