name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            chicagozer/hellonode
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: checkout TG
        uses: actions/checkout@v3
        with:
          repository: Xtime/harness-tg
          path: "./harness-tg/"
          ref: master
          token: ${{ secrets.GH_TOKEN }}
      - name: bump version
        uses: jossef/action-set-json-field@v1
        with:
          file: rtdbtg/terragrunt/appversion.tfvars.json
          field: app_version.hellonode
          value: sha-${{ steps.vars.outputs.sha_short }}
#      - name: check in
#        uses: EndBug/add-and-commit@v9
#        with:
#          message: "check in from GHA"
#          add: "terragrunt/appversion.tfvars.json"
#          cwd: "./harness-tg/"
      - name: check in
        uses: actions/checkout@v3
        run: |
          cd rtdbtg
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
