name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  AWS_ACCOUNT: "015614266771"
  AWS_REGION: us-east-2

jobs:
  docker:
    runs-on: [ CAI-Enterprise ]
    steps:
      - run: env
      - name: set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Create TLS context
        run: docker context create tls-environment
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          driver: docker-container
          endpoint: tls-environment
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Configure AWS Secure Access
        uses: cai-actions/aws-secure-access@v1
        with:
          account: "${{env.AWS_ACCOUNT}}"
          region: ${{env.AWS_REGION}}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            015614266771.dkr.ecr.us-east-2.amazonaws.com/hellonode
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: checkout TG
        uses: actions/checkout@v3
        with:
          repository: Xtime/harness-tg
          path: "./harness-tg/"
          ref: master
          token: ${{ secrets.GH_TOKEN }}
#      - name: bump version
#        uses: jossef/action-set-json-field@v1
#        with:
#          file: rtdbtg/terragrunt/appversion.tfvars.json
#          field: app_version.hellonode
#          value: sha-${{ steps.vars.outputs.sha_short }}
#      - name: check in
#        uses: EndBug/add-and-commit@v9
#        with:
#          message: "updated by GHA @ ${{ GITHUB_REPOSITORY }}"
#          add: "terragrunt/appversion.tfvars.json"
#          cwd: "./harness-tg/"
      - name: check in
        run: |
          jq  ".app_version.hellonode = \"sha-${{ steps.vars.outputs.sha_short }}\"" ./harness-tg/terragrunt/appversion.tfvars.json > appvars.auto.tfvars.json.tmp
          mv -f appvars.auto.tfvars.json.tmp ./harness-tg/terragrunt/appversion.tfvars.json
          cd harness-tg
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "updated by GHA $GITHUB_REPOSITORY"
          git push --set-upstream origin master
