name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chicagozer/hellonode:latest
      -
        name: checkout TG
        uses: actions/checkout@v3
        with:
          repository: chicagozer/rtdbtg
          path: './rtdbtg/'
          ref: main
          token: ${{ secrets.GH_TOKEN }}
      -
        name: bump version
        uses: jossef/action-set-json-field@v1
        with:
          file: rtdbtg/terragrunt/appversion.tfvars.json
          field: app_version.hellonode
          value: latest
      - 
        name: check in
        uses: EndBug/add-and-commit@v9
        with:
          message: 'check in from GHA'
          add: 'terragrunt/appversion.tfvars.json'
          cwd: './rtdbtg/'
